/* Auto-generated DE60 White layout variants grouped by R4 family */


/* ===================================================== */
/* GROUP: 625U_U */
/* ===================================================== */

#define WHITE_LAYOUT_625U_U_BS_1U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_1U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_U

#define WHITE_LAYOUT_625U_U_BS_2U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_U


/* ===================================================== */
/* GROUP: 625U_A */
/* ===================================================== */

#define WHITE_LAYOUT_625U_A_BS_1U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_1U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_A

#define WHITE_LAYOUT_625U_A_BS_2U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_A


/* ===================================================== */
/* GROUP: 625U_H */
/* ===================================================== */

#define WHITE_LAYOUT_625U_H_BS_1U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_1U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_625U_H

#define WHITE_LAYOUT_625U_H_BS_2U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_625U_H


/* ===================================================== */
/* GROUP: 7U_WK */
/* ===================================================== */

#define WHITE_LAYOUT_7U_WK_BS_1U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_1U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WK

#define WHITE_LAYOUT_7U_WK_BS_2U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WK


/* ===================================================== */
/* GROUP: 7U_WKL */
/* ===================================================== */

#define WHITE_LAYOUT_7U_WKL_BS_1U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_1U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_WKL

#define WHITE_LAYOUT_7U_WKL_BS_2U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_WKL


/* ===================================================== */
/* GROUP: 7U_HHKB */
/* ===================================================== */

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_1U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_HHKB

#define WHITE_LAYOUT_7U_HHKB_BS_2U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_HHKB


/* ===================================================== */
/* GROUP: 7U_ARROW */
/* ===================================================== */

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_1U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_7U_ARROW

#define WHITE_LAYOUT_7U_ARROW_BS_2U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_7U_ARROW


/* ===================================================== */
/* GROUP: 10U_WK */
/* ===================================================== */

#define WHITE_LAYOUT_10U_WK_BS_1U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_1U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WK

#define WHITE_LAYOUT_10U_WK_BS_2U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WK


/* ===================================================== */
/* GROUP: 10U_WKL */
/* ===================================================== */

#define WHITE_LAYOUT_10U_WKL_BS_1U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_1U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_WKL

#define WHITE_LAYOUT_10U_WKL_BS_2U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_WKL


/* ===================================================== */
/* GROUP: 10U_HHKB */
/* ===================================================== */

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_1U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_1U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ANSI_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ANSI_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ANSI_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ANSI_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ANSI_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ANSI_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ANSI_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ANSI_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ANSI_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ANSI_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ANSI_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ANSI_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ANSI \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ISO_ANSI_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ISO_ANSI_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ISO_ANSI_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ISO_ANSI_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ISO_ANSI_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ISO_ANSI_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ANSI \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ISO_ISO_ANSI_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ISO_ISO_ANSI_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ISO_ISO_ANSI_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ANSI_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ISO_ISO_ISO_175U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_175U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ISO_ISO_ISO_275U \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_275U \
    WHITE_LAYOUT_R4_10U_HHKB

#define WHITE_LAYOUT_10U_HHKB_BS_2U_ISO_ISO_ISO_ARROW \
    WHITE_LAYOUT_R0_BS_2U \
    WHITE_LAYOUT_R1_ISO \
    WHITE_LAYOUT_R2_ISO \
    WHITE_LAYOUT_R3_ISO_ARROW \
    WHITE_LAYOUT_R4_10U_HHKB
